CREATE DATABASE IF NOT EXISTS BLOXCROSS
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE BLOXCROSS;

CREATE TABLE IF NOT EXISTS BLOX_CREDENTIALS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(100),
    BASE_URL VARCHAR(250) NOT NULL,
    CLIENT_ID VARCHAR(250) NOT NULL,
    API_KEY VARCHAR(500) NOT NULL,
    SECRET_KEY VARCHAR(500) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE BLOX_CREDENTIALS
ADD COLUMN IF NOT EXISTS SECRET_KEY VARCHAR(500) NOT NULL DEFAULT '';


INSERT INTO BLOX_CREDENTIALS
(`NAME`, BASE_URL, CLIENT_ID, API_KEY, SECRET_KEY, IS_ACTIVE)
VALUES 
('Bloxcross', 'https://api.bloxcross-dev.com', 'your_client_id', 'your_api_key', 'your_secret_key', TRUE);


CREATE TABLE IF NOT EXISTS `API_LOG` (
  `API_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `API_METHOD_NAME` VARCHAR(70) DEFAULT NULL,
  `API_PARAMETERS` TEXT,
  `API_RESPONSE` TEXT,
  `API_IP_ADDRESS` VARCHAR(30) DEFAULT NULL,
  `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `API_TRACE_ID` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`API_ID`),
  KEY `idx_api_method_name` (`API_METHOD_NAME`),
  KEY `idx_api_trace_id` (`API_TRACE_ID`),
  KEY `idx_create_date` (`CREATE_DATE`),
  KEY `idx_ip_address` (`API_IP_ADDRESS`),
  FULLTEXT KEY `API_PARAMETERS` (`API_PARAMETERS`,`API_RESPONSE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `DEPOSITS` (
  `ID` CHAR(36) NOT NULL,
  `CURRENCY` VARCHAR(20) NOT NULL,
  `AMOUNT` DECIMAL(18,8) NOT NULL,
  `STATUS` VARCHAR(50) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `WEBHOOK_LOGS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EVENT_TYPE` VARCHAR(100) NOT NULL,
  `TRANSACTION_ID` VARCHAR(100) NOT NULL,
  `PORTFOLIO_ID` VARCHAR(100) NOT NULL,
  `AMOUNT` DECIMAL(18,8) NOT NULL,
  `CURRENCY` VARCHAR(20) NOT NULL,
  `STATUS` VARCHAR(50) NOT NULL,
  `RAW_PAYLOAD` LONGTEXT NOT NULL,
  `RECEIVED_AT` DATETIME NOT NULL,
  `PROCESSED_AT` DATETIME NULL,
  `ERROR_MESSAGE` LONGTEXT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_WEBHOOK_LOGS_TRANSACTION_ID` (`TRANSACTION_ID`),
  KEY `IDX_WEBHOOK_LOGS_PORTFOLIO_ID` (`PORTFOLIO_ID`),
  KEY `IDX_WEBHOOK_LOGS_RECEIVED_AT` (`RECEIVED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
